### ISSUE TITLE
SQL Error upon submitting MBLD result

### ISSUE THREAD

**Issue by timwongj** [cubing/CubePB#13]
Here's a screenshot:

<img width="1680" alt="Screen Shot 2021-04-08 at 12 40 03 AM" src="https://user-images.githubusercontent.com/9956561/113969455-0750ed00-9803-11eb-846f-fbc8018c415b.png">

**Comment by big213** [comment]
Thanks for reporting this, let me look into getting this fixed

**Comment by big213** [comment]
Should be fixed now, lmk if there's any other issues!
