### ISSUE TITLE
Error saving PBS

### ISSUE THREAD

**Issue by Quinism** [cubing/CubePB#17]
Here's a rundown of this bug as best as I can.

I set 2 PBs on 4x4 in the same day. The times are 1:19.25 followed by a slightly faster 1:19.07. I try to save them and get this exact error message:

GiraffeqlBaseError: Score must be worse than future scores.

It lets me save the PB as happening tomorrow but I'm unable to save them on the same day.

**Comment by big213** [comment]
![image](https://user-images.githubusercontent.com/8443042/114771308-67cbb700-9d3a-11eb-8869-c0d4541f06ed.png)

Try adding the exact time of the 2nd PB, like shown. This will allow the system to recognize your 2nd PB as a technically "later" PB.

**Comment by big213** [comment]
I've just applied a change in 2744f9b that should prevent this issue going forward. This feature will be available as of v0.1.23 or later
