### ISSUE TITLE
discord link invalid

### ISSUE THREAD

**Issue by effperm** [cubing/CubePB#2]

**Comment by big213** [comment]
Which link are you seeing? The correct one is this: https://discord.com/invite/72d8gNq7bh

(try hitting ctrl + f5 to hard refresh the page and see if the correct one shows up)

**Comment by effperm** [comment]
im using the one in the front page
this one to be exact
![751FB0CB-C221-4AEA-86D8-BF14FD059D40](https://user-images.githubusercontent.com/77275623/112722236-3e8de700-8f43-11eb-954c-353a9529cfd3.jpeg)
